name: build&deploy to master

on:
  push:
    branches:
      - master

env:
  SERVICE_NAME: "intens"
  DOCKERHUB_USERNAME: "msquare1009"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Mandatory to use the extract version from tag action 
      # Extract build version
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      - name: Extract Version
        id: version_step
        run: |
          echo "version=$(echo $MAJOR.$MINOR.$(($PATCH + $NUMBER_OF_COMMITS_SINCE_TAG)))" >> $GITHUB_OUTPUT
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF_NAME}}" >> $GITHUB_OUTPUT
      - name: Print Version
        run: |
          echo ${{steps.version_step.outputs.version}}
      # Require Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      # Require Docker
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      # Docker login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: PrepareReg Names
        id: read-docker-image-identifiers
        run: |
          echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      # Build the image and push to Dockerhub
      - name: Build docker image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{env.DOCKERHUB_USERNAME}}/${{env.SERVICE_NAME}}:${{env.VERSION_TAG}}_${{github.ref_name}}
          build-args: |
            ${{steps.version_step.outputs.version}}